### ISSUE TITLE
[Tracking] Script and config updates to support simplified selection of "features"

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1044]
As a part of https://github.com/microsoft/vscode-remote-release/issues/5442, this is a tracking issue to track updates to scripts and `features.json` before we do an initial test what we are colloquially calling the "Lego Blocks" concept.

- [ ] Update versions - e.g. Go 1.17 released
- [ ] Add Docker Compose-based definitions to include list for each feature - e.g. javascript-node-mongodb
- [ ] Allow selection of a Kubernetes MAJOR.MINOR version, use that for kubectl and minikube
    - [ ] Minikube no longer requires Docker, so thankfully we can remove this requirement from the script.
    - [ ] If we are able to pick independent versions (as discussed in https://github.com/microsoft/vscode-remote-release/issues/5442), we could surface the ability to pick a Helm version separately.
- [ ] Allow selection of a Terraform version, just use latest for tflint/tfgrunt
    - [ ] If we are able to pick independent versions (as discussed in https://github.com/microsoft/vscode-remote-release/issues/5442), we could surface the ability to pick TFLint/TFGrunt.
- [ ] Add version selection to PowerShell (though limited)
- [ ] Add version selection to Docker (DinD and DfD)  (`github-debian.sh` is an example that installs a version using apt-get)
    -  [ ] Add "Use the OSS Moby CLI instead of the licensed Docker CLI" option if we can, otherwise default to Moby
- [ ] Add distro check for each script, provide good error message when not supported (e.g. Debian stretch is not supported by Docker scripts - no recent builds)
- [ ] Update options text with final values from @2percentsilk

//cc: @2percentsilk @bamurtaugh @chrmarti - Feel free to add others to this list.
