### ISSUE TITLE
[Tracking] Misc script library tasks

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#560]
There are a series of improvements that need to be made to the library scripts. This issue is for tracking.

- [x] Add a SSH script (#553)
- [x] Add a light weight Linux desktop script (#554)
- [x] Fix `code` alias in Zsh and Fish (#557)
- [x] Add Oh My Bash! into the common script ([bash-it has no license](https://github.com/Bash-it/bash-it/issues/512), so can't use)
- [x] Default to non-root user (#552)
- [x] Be smarter about identifying a non-root user (look up UID 1000 if no user name specified)
- [ ] Switch to pyenv for Python script (#533)
- [ ] Adapt devcontainer.json and Dockerfile comments to cover using an interactive shell for nvm, sdkman, etc (#559)
- [x] Add documentation for scripts explaining usage #563 
- [ ] <strike>Switch ssh script to default to port 22 in codespaces-linux once this is possible</strike> (Not doing this since it would conflict with local ports anyway.)
